---
- hosts: 192.168.0.32
  tasks:
    - name: installing httpd package
      package: name=httpd state=present
    - name: starting httpd service
      service: name=httpd state=started  enabled=yes
    - name: installing git
      package: name=git state=present
    - name: download git repo
      git: repo=https://github.com/demoglot/html-samples-food.git dest=/var/www/html
    - name: stopfirewalld
      service: name=firewalld state=stopped 

